name: packages testing

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '18'
          cache: 'yarn'
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Check Yarn version
        run: yarn --version
      - name: Check Node version
        run: node --version
      - name: Install dependencies
        run: yarn install
      - name: Execute lint
        run: yarn lint

      - name: Cache power of tau
        id: powersOfTau28_hez_final_20
        uses: actions/cache@v3
        with:
          path: packages/circuits/build/powersOfTau28_hez_final_20.ptau
          key: powersOfTau28_hez_final_20.ptau
      - name: Cache Circom
        id: Circom
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin/circom
          key: circom

      - name: Download power of tau and install Circom
        run: cd packages/circuits && yarn dev-install

      - name: Get Circuit Hash
        id: get-circuit-hash
        run: |
          echo "circuits_hash=`cd packages/circuits && ./scripts/utils.sh`" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache proving/verify key
        id: zkkeys
        uses: actions/cache@v3
        with:
          path: packages/circuits/build
          key: ${{ steps.get-circuit-hash.outputs.circuits_hash }}

      - name: Create .env file for contracts tests
        run: |
          echo "PROVIDER_KEY=$PROVIDER_KEY_SECRET" > ./packages/contracts/.env
        env:
          PROVIDER_KEY_SECRET: ${{secrets.PROVIDER_KEY}}

      - name: Build circuits
        run: cd packages/circuits && yarn build-circuit

      - name: Run development trusted setup
        run: yarn dev-setup:circuit

      - name: Build packages
        run: yarn build:libraries

      - name: Test /circuits
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        working-directory: packages/circuits
        run: yarn test

      - name: Test /core
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        working-directory: packages/core
        run: yarn test

      - name: Test /contracts
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        working-directory: packages/contracts
        run: yarn test

      - name: Test /react
        env:
          NODE_OPTIONS: '--max_old_space_size=8192'
        working-directory: packages/react
        run: yarn test
