name: Publish to npm

on:
  release:
    types:
      - created

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '18' # Use the appropriate Node version for your project
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Check Yarn version
        run: yarn --version
      - name: Check Node version
        run: node --version
      - name: Install dependencies
        run: yarn install
      - name: Execute lint
        run: yarn lint

      - name: Authenticate and publish to npm
        run: |
          echo "npmAuthToken: $NODE_AUTH_TOKEN" >> ~/.yarnrc.yml
          yarn publish:libraries
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
